# Generated by Django 5.0 on 2024-11-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copyright_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_designer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='illustrator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lccn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Library of Congress Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='printing_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publisher_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publisher_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publisher_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rights_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='version_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PDFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A5', 'A5 (148x210mm)'), ('LETTER', 'Letter (216x279mm)'), ('CUSTOM', 'Custom Size')], default='A4', max_length=10)),
                ('custom_width', models.FloatField(blank=True, help_text='Width in mm', null=True)),
                ('custom_height', models.FloatField(blank=True, help_text='Height in mm', null=True)),
                ('margin_top', models.FloatField(default=25.4, help_text='Top margin in mm')),
                ('margin_right', models.FloatField(default=25.4, help_text='Right margin in mm')),
                ('margin_bottom', models.FloatField(default=25.4, help_text='Bottom margin in mm')),
                ('margin_left', models.FloatField(default=25.4, help_text='Left margin in mm')),
                ('columns', models.IntegerField(choices=[(1, 'Single Column'), (2, 'Two Columns'), (3, 'Three Columns')], default=1)),
                ('column_spacing', models.FloatField(default=12.7, help_text='Space between columns in mm')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('footer_text', models.CharField(blank=True, max_length=200)),
                ('include_page_numbers', models.CharField(choices=[('NONE', 'No Page Numbers'), ('SIMPLE', 'Simple Numbers'), ('CHAPTER', 'Chapter-based (1-1, 1-2)'), ('ROMAN', 'Roman Numerals')], default='SIMPLE', max_length=10)),
                ('chapter_start_new_page', models.BooleanField(default=True)),
                ('chapter_title_font_size', models.IntegerField(default=24)),
                ('chapter_title_spacing', models.FloatField(default=25.4, help_text='Space after chapter title in mm')),
                ('generate_toc', models.BooleanField(default=True)),
                ('include_index', models.BooleanField(default=False)),
                ('include_bleed_marks', models.BooleanField(default=False)),
                ('bleed_size', models.FloatField(default=3, help_text='Bleed size in mm')),
                ('include_trim_marks', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_settings', to='books.project')),
            ],
        ),
    ]
