# Generated by Django 5.0 on 2024-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_project_copyright_text_project_cover_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
